- name: install 1password
  shell:
    cmd: |
      curl -Lo /tmp/1password.deb "https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb" && sudo apt install -y /tmp/1password.deb && rm /tmp/1password.deb
  become: true
