- name: update repositories
  apt:
    update_cache: yes
  become: true

- name: Install minimum packages with apt
  apt:
    name: "{{ apt_minimum_packages }}"
    state: present
    update_cache: true
  become: true

- name: adding existing user to group mail
  user:
    name: "{{ ansible_user_id }}"
    groups: mail
    append: yes
  become: true
