- name: get latest lazygit version
  ansible.builtin.uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    return_content: yes
  register: lazygit_release

- name: download lazygit
  ansible.builtin.unarchive:
    src: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_release.json.tag_name | regex_replace('^v', '') }}_Linux_x86_64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    include: lazygit
    creates: /usr/local/bin/lazygit
  become: true
