# Not sure this worked, this is probably obsolete.
# check https://askubuntu.com/questions/207442/how-to-add-open-terminal-here-to-nautilus-context-menu

# ---
# - name: Install nautilus-open-terminal on Ubuntu
#   hosts: localhost
#   become: yes  # Enables sudo for the tasks
#   tasks:
#     - name: Add universe repository
#       ansible.builtin.apt_repository:
#         repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
#         state: present
#         update_cache: no  # We'll handle cache update in a separate task
#       register: add_repo
#       changed_when: add_repo.changed

#     - name: Update apt cache
#       ansible.builtin.apt:
#         update_cache: yes
#       register: apt_update
#       changed_when: apt_update.cache_updated

#     - name: Install nautilus-open-terminal
#       ansible.builtin.apt:
#         name: nautilus-open-terminal
#         state: present