- name: Bootstrap development environment
  hosts: localhost
  become: yes
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
  tasks:
  - name: add lazygit ppa
    apt_repository:
      repo: 'ppa:lazygit-team/release'
  - name: add telegram
    apt_repository:
      repo: 'ppa:atareao/telegram'
  - name: Install packages with apt
    become: yes
    apt:
      name:
        - git
        - tmux
        - vim
        - mc
        - terminator
        - python3.8
        - flameshot
        - lazygit
        - telegram
        - vlc
      state: present
      update_cache: true
