dotfiles_link_ssh_config: false

# Apps to remove from /Applications (non-SIP protected)
macos_remove_apps:
  - GarageBand
  - iMovie
  - Keynote
  - Numbers
  - Pages
  - "Photo Booth"
  - Chess

# Launch daemons to disable
macos_disable_daemons:
  - com.apple.rapport
  - com.apple.mediaanalysisd
  - com.apple.cloudphotod
  - com.apple.photolibraryd

macos_disable_spotlight: true
macos_disable_siri: true
macos_disable_game_center: true

brew_cask_packages:
  - google-chrome
  - keepassx
  - tailscale

brew_packages:
  - atuin
  - bat
  - btop
  - dust
  - eza
  - fastfetch
  - fd
  - fzf
  - git
  - git-crypt
  - git-delta
  - git-lfs
  - jq
  - ripgrep
  - tealdeer
  - tmux
  - tmuxinator
  - tree
  - wget
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-syntax-highlighting
