brew_cask_packages:
  - google-chrome
  - keepassx
  - tailscale

brew_packages:
  - atuin
  - bat
  - btop
  - dust
  - eza
  - fastfetch
  - fd
  - fzf
  - git
  - git-crypt
  - git-delta
  - git-lfs
  - jq
  - ripgrep
  - tealdeer
  - tmux
  - tmuxinator
  - tree
  - wget
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-syntax-highlighting
