- name: cursor config
  hosts: localhost
  become: false
  tasks:
    - name: ensure directory
      become: no
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/Cursor"
        state: directory
    - name: Creating hardlink
      become: no
      ansible.builtin.file:
        src: "~/dotfiles/cursor/settings.json"
        dest: "~/.config/Cursor/settings.json"
        state: link
